<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260413030422 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE contributor (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, contributor_order INT NOT NULL, display_name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE departement (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, url VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, end_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, content VARCHAR(5000) NOT NULL, title VARCHAR(255) NOT NULL, event_type VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE institution (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, url VARCHAR(255) DEFAULT NULL, departement_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3A9F98E5CCF9E01E ON institution (departement_id)');
        $this->addSql('CREATE TABLE news (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content VARCHAR(5000) NOT NULL, published_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, title VARCHAR(255) NOT NULL, image_path VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE person (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, biography VARCHAR(2500) DEFAULT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, email VARCHAR(180) DEFAULT NULL, photo_path VARCHAR(255) DEFAULT NULL, job_title VARCHAR(150) DEFAULT NULL, personal_page_url VARCHAR(255) DEFAULT NULL, role VARCHAR(255) NOT NULL, institution_id INT DEFAULT NULL, departement_id INT DEFAULT NULL, student_profile_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_34DCD17610405986 ON person (institution_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_34DCD176CCF9E01E ON person (departement_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_34DCD1762125FF59 ON person (student_profile_id)');
        $this->addSql('CREATE TABLE project (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, summary VARCHAR(2500) DEFAULT NULL, funding_source VARCHAR(255) DEFAULT NULL, is_finished BOOLEAN NOT NULL, title VARCHAR(255) NOT NULL, thematic VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE publication (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, year INT NOT NULL, external_url VARCHAR(255) DEFAULT NULL, publication_type VARCHAR(255) NOT NULL, contributor_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AF3C67797A19A357 ON publication (contributor_id)');
        $this->addSql('CREATE TABLE student_degree (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, start_year INT NOT NULL, end_year INT DEFAULT NULL, degree VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE student_profile (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, supervisor VARCHAR(255) DEFAULT NULL, co_supervisor VARCHAR(255) DEFAULT NULL, student_degree_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6C611FF7D43296D6 ON student_profile (student_degree_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE institution ADD CONSTRAINT FK_3A9F98E5CCF9E01E FOREIGN KEY (departement_id) REFERENCES departement (id)');
        $this->addSql('ALTER TABLE person ADD CONSTRAINT FK_34DCD17610405986 FOREIGN KEY (institution_id) REFERENCES institution (id)');
        $this->addSql('ALTER TABLE person ADD CONSTRAINT FK_34DCD176CCF9E01E FOREIGN KEY (departement_id) REFERENCES departement (id)');
        $this->addSql('ALTER TABLE person ADD CONSTRAINT FK_34DCD1762125FF59 FOREIGN KEY (student_profile_id) REFERENCES student_profile (id)');
        $this->addSql('ALTER TABLE publication ADD CONSTRAINT FK_AF3C67797A19A357 FOREIGN KEY (contributor_id) REFERENCES contributor (id)');
        $this->addSql('ALTER TABLE student_profile ADD CONSTRAINT FK_6C611FF7D43296D6 FOREIGN KEY (student_degree_id) REFERENCES student_degree (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE institution DROP CONSTRAINT FK_3A9F98E5CCF9E01E');
        $this->addSql('ALTER TABLE person DROP CONSTRAINT FK_34DCD17610405986');
        $this->addSql('ALTER TABLE person DROP CONSTRAINT FK_34DCD176CCF9E01E');
        $this->addSql('ALTER TABLE person DROP CONSTRAINT FK_34DCD1762125FF59');
        $this->addSql('ALTER TABLE publication DROP CONSTRAINT FK_AF3C67797A19A357');
        $this->addSql('ALTER TABLE student_profile DROP CONSTRAINT FK_6C611FF7D43296D6');
        $this->addSql('DROP TABLE contributor');
        $this->addSql('DROP TABLE departement');
        $this->addSql('DROP TABLE event');
        $this->addSql('DROP TABLE institution');
        $this->addSql('DROP TABLE news');
        $this->addSql('DROP TABLE person');
        $this->addSql('DROP TABLE project');
        $this->addSql('DROP TABLE publication');
        $this->addSql('DROP TABLE student_degree');
        $this->addSql('DROP TABLE student_profile');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
