name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: app_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: pdo, pdo_mysql, intl, zip

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Check env file
        run: cp .env .env.test.local

      - name: Run migrations
        env:
          DATABASE_URL: mysql://root:root@127.0.0.1:3306/app_test?serverVersion=8.0&charset=utf8mb4
        run: php bin/console doctrine:migrations:migrate --no-interaction

      - name: Run tests
        env:
          DATABASE_URL: mysql://root:root@127.0.0.1:3306/app_test?serverVersion=8.0&charset=utf8mb4
        run: php bin/phpunit